### PR TITLE
Update chill.p8

### PR DESCRIPTION
**Pull request by JonTerp**
FIXED INACCURATE CREDITS

### CODE REVIEW

**Comment by buffis** [comment]
I dunno, the other dudes are PRETTY chill.
I WOULD be fine with adding you to the chill dudes list though!

**Comment by JonTerp** [comment]
I mean I was pretty clear on this in IRC. The god king demands unfair credit, else the vampire judging cabal will frown upon your home.

**Comment by buffis** [comment]
I could be convinced to oblige the godking, but I would surely deserve some awards for my offering?

**Comment by JonTerp** [comment]
Being spared by # THE CABAL is reward enough.

**Pull request closed without merging**
